services:
  homelab-portal:
    image: ghcr.io/kmasouri/homelab-portal:latest
    ports:
      - '80:80'
    volumes:
      - ./homelab-portal-config.json:/usr/share/nginx/html/config.json:ro
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  network:
    driver: overlay
    attachable: true
